repos:
  - repo: local
    hooks:
      - id: ruff-format
        name: ruff (format)
        entry: ruff format
        language: python
        types: [python]
        additional_dependencies: [ruff]
        exclude: \.toml$
      - id: ruff
        name: ruff (lint)
        entry: ruff check
        language: python
        types: [python]
        additional_dependencies: [ruff]
        exclude: \.toml$
      - id: pipreqs
        name: pipreqs (generate requirements.txt)
        entry: bash -c 'pipreqs . --force --encoding=utf-8 --mode no-pin'
        language: system
        pass_filenames: false
        types: [python]
